### PR TITLE
search function

### PR DESCRIPTION
**Pull request by IniZio**
Add search function to header

### CODE REVIEW

**Comment by viko16** [comment]
Good idea ! But if you change the title, how can i turn back to `List view` when i am in `Post view` ?

唔，这个想法很好，但是原本的 Title 是充当回到首页的作用，如果把 Title 变作搜索栏的话，在 Post 页怎么回去呢？

**Comment by viko16** [comment]
I think, add a new search bar will be better ?

**Comment by IniZio** [comment]
因爲想盡量簡單頁面. 或者我看看有沒有其他方法?

**Comment by IniZio** [comment]
Made search bar an additional part instead of replacing title, esc exits the search bar and resets keyword

**Comment by viko16** [comment]
👍

**Comment by viko16** [comment]
@IniZio What's the meaning of `tag="h1" to="/"`?

**Comment by IniZio** [comment]
Sorry should not have that part D:

**Pull request merged**
